apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    provider: aks
  environments:
    - key: dev
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls: {}
  secretStorage: vault
  vault: {}
